### ISSUE TITLE
Suggestion for new feature

### ISSUE THREAD

**Issue by Nikit-Singh** [PapiCZ/pastitude#1]
Can you add an **automatic url shortener**  to the generated files so that they are easy to share with others?
And great work btw. 👌👍

**Comment by PapiCZ** [comment]
It's good idea, but unfortunately it's not possible.

ID of paste has only 8 chars, which is short enough.
And decryption key (string after `#` char) can't be stored in database, because it would break **end-to-end** encryption. (Un)fortunately decryption key is random, so there's no chance to compress it.
